color: orange
description: null
fieldLayouts:
  90e0e39d-65c9-4fcc-8d6a-e641d08c2f43:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-18T12:40:15+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 79b79154-5b26-4a51-89c3-66cf807014af # Images
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b8d6efb4-2958-4af8-bc7d-70882b9d2432
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0b5cd942-d5db-4b5c-aab1-13d7474d6eb2
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-11-21T09:47:27+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3c6dd0d6-6cbf-415f-a6fe-3bc205817b94 # Anchor
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5133c3f6-fd2e-47c3-9875-d3e52e2c5bb6
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 8b24c193-0993-4005-b49a-c22b4d4da935
        userCondition: null
handle: blockGallery
hasTitleField: false
icon: images
name: Gallery
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
