color: green
description: null
fieldLayouts:
  8d175b23-bd0d-4592-ab6e-1d29c5954c4c:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-10-21T11:08:10+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a7138906-a7ad-4e1c-8e6a-376b76a0547c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-21T11:08:10+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a44cd88c-10a5-4ee3-b9e4-795e2f4f208c # Code
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e7459ed4-df67-4211-b658-48349ffdf644
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c6fdfdeb-75c5-47f5-87cc-3c7498792dec
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-11-21T09:46:42+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3c6dd0d6-6cbf-415f-a6fe-3bc205817b94 # Anchor
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c40f5fe5-a75d-4b08-91b1-c5ec3d5a8642
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: c5bdf99b-3b02-450d-b818-832fc94ebdc1
        userCondition: null
handle: blockCode
hasTitleField: true
icon: code
name: Code
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
