color: null
description: null
fieldLayouts:
  9d9f2ba5-39cd-4fa0-a99a-7d19974524a6:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-11-07T09:22:09+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1846279a-ea81-4926-a068-da62ba41e70a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-07T09:24:35+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7cdf6921-13c4-4984-95cd-9ac60231929d # Rich Text - Builder
            handle: builder
            includeInCards: false
            instructions: null
            label: Text
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2b51574c-5057-4c70-9a63-3e3612eb11b0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: fe3e120a-7bdd-4df4-b08d-93509adef63a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-11-07T09:24:35+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5bf4ae8e-4fcb-4ed0-bb07-7dbbb4c59050 # Seo
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: df98a1bb-b885-4c11-8809-fe2caf178e8c
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 54e6a6fe-f63e-4b37-b47f-b0db946e8569
        userCondition: null
handle: etMap
hasTitleField: true
icon: location-dot
name: Map
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
