color: null
description: null
fieldLayouts:
  5fe18ecd-919d-4295-bd74-1a05649cc570:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-10-06T12:33:59+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 45b0ae5f-50b4-4876-9aa6-655b32456bbf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-06T12:38:14+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 17c0c6a4-80a6-4cef-84f4-ebefe3af9d39 # Text - Multi
            handle: headline
            includeInCards: false
            instructions: null
            label: Headline
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c67defbb-160e-48ab-9dc8-7a4dc6e8db58
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-06T12:38:14+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6243b5f2-9474-47a0-99f2-24d5a6cc5832 # Rich Text - Rich
            handle: text
            includeInCards: false
            instructions: null
            label: Text
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b999da82-f3cc-42df-bf8b-7302ef816953
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4cd0345e-3357-44b2-93d3-082169bb6dc2
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-10-07T09:20:54+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5bf4ae8e-4fcb-4ed0-bb07-7dbbb4c59050 # Seo
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 24b47791-7057-4a0e-93ba-a21799e438e1
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: d8de2eb9-2732-4291-8411-931d5d91ce1f
        userCondition: null
handle: etPageBlogDatastar
hasTitleField: true
icon: page
name: 'Page / Blog Datastar'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
