color: null
description: null
fieldLayouts:
  bc9fe2d1-76ca-48b0-94c7-a821f8e6dd12:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-10-02T10:56:53+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c2ba1d03-58f8-4834-8a91-ba5aba3afdd5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-02T11:00:29+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7cdf6921-13c4-4984-95cd-9ac60231929d # Rich Text - Builder
            handle: builder
            includeInCards: false
            instructions: null
            label: 'CKE Builder'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 07a9b258-5c86-435c-bd6b-ca038ff4e5e9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 365e47cc-afa2-4678-a178-0b501a13343d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-10-07T09:21:38+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5bf4ae8e-4fcb-4ed0-bb07-7dbbb4c59050 # Seo
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 12c04073-2a7f-4ecf-be11-e77788aded62
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 17003983-77af-4170-975f-13ceeb0106d4
        userCondition: null
handle: etPageCke
hasTitleField: true
icon: page
name: 'Page / CKE Builder'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
