color: null
description: null
fieldLayouts:
  1524573c-4edb-429d-82ee-9d82c4273a52:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-18T12:40:35+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 37109913-e017-4312-a994-795cedebef7c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-14T11:40:09+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 17c0c6a4-80a6-4cef-84f4-ebefe3af9d39 # Text - Multi
            handle: headline
            includeInCards: false
            instructions: null
            label: Headline
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 872f39e9-c6e7-4db6-9915-33944177d829
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-18T12:40:35+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0a5600e8-07a6-4292-bc21-d0e142d9dc22 # Matrix - Builder
            handle: null
            includeInCards: false
            instructions: null
            label: 'Matrix Builder'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c82356b3-dcb0-4cb1-b19f-4213e87e1719
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 96ef25c5-43c8-45c4-98db-c8705cb35a2e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-10-07T09:21:56+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5bf4ae8e-4fcb-4ed0-bb07-7dbbb4c59050 # Seo
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b393f0f5-888a-46a4-8cef-e79de7f19f81
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: f073ef3c-d8ce-4295-9b93-7bbdabe73918
        userCondition: null
handle: etPageMatrix
hasTitleField: true
icon: page
name: 'Page / Matrix Builder'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
