color: null
description: null
fieldLayouts:
  e72bc2b7-5f59-4219-951e-101c3683fc64:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-10-07T08:33:58+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 486a1585-5cef-4f53-bdd5-12f7cf4d0dda
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-07T08:37:23+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 17c0c6a4-80a6-4cef-84f4-ebefe3af9d39 # Text - Multi
            handle: headline
            includeInCards: false
            instructions: null
            label: Headline
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f8fa90ba-e624-4c6b-82e5-806c7c869935
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-07T08:37:23+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6243b5f2-9474-47a0-99f2-24d5a6cc5832 # Rich Text - Rich
            handle: text
            includeInCards: false
            instructions: null
            label: Text
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d5e6d8c8-d270-4cb5-9e6f-84c64de0bafa
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 807b8fe0-b5d9-40ae-970e-cdc3307ebe8b
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-10-07T09:21:22+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5bf4ae8e-4fcb-4ed0-bb07-7dbbb4c59050 # Seo
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8c643070-e562-4f9e-95c3-9795d071a150
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 57fe9c6d-4d2b-443b-807d-927cf2cb06cc
        userCondition: null
handle: etPageBlogVue
hasTitleField: true
icon: page
name: 'Page / Blog Vue'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
