color: null
description: null
fieldLayouts:
  a3454708-32a0-4b9d-87ba-9379d21244ac:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-10-09T10:06:42+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a00bc4e7-9f4d-4425-ad4a-8062763a8ec3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-09T10:08:41+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7cdf6921-13c4-4984-95cd-9ac60231929d # Rich Text - Builder
            handle: builder
            includeInCards: false
            instructions: null
            label: Text
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fba4e9d8-e8fa-4067-b5f1-c9b9a2a562d1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4dc04a7f-dbef-41c0-a91b-32b60b290595
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-10-09T10:08:41+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5bf4ae8e-4fcb-4ed0-bb07-7dbbb4c59050 # Seo
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e6ad85d1-5016-46a8-878e-e07cffa38bcb
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: e7c8647a-918c-4507-bb16-9cecb1a2f0d4
        userCondition: null
handle: etSearch
hasTitleField: true
icon: magnifying-glass
name: Search
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
