defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: a9a428eb-cbae-455e-876a-3cef2b1fef95 # Map
handle: map
maxAuthors: 1
name: Map
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  6eab4b84-63fb-4382-bdd7-d2bee959aafb: # $SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: _entry/index.twig
    uriFormat: map
type: single
